### ISSUE TITLE
shouldn't delete really be deleteMany?

### ISSUE THREAD

**Issue by bryanmi** [battlesnake/node-mysql-orm#22]
//     deleteMany(schema.users, { role: { name: 'guest' } }, callback);
// 
// 
ORM.prototype.delete = function () {

**Comment by battlesnake** [comment]
Probably.  I'm planning a re-write of this module at some point as it is a pile of spaghetti.  When I get around to that, I'll try to enforce via SQL that non-"many" operations must either affect exactly one record, or fail with useful error.

**Comment by bryanmi** [comment]
hi


thanks for the response.

i did have another question if you can oblige…

i am trying to only update some columns in a table and when using something like:

database.save("status", { _id : 0, name : 'server', state: 'updating' }, function (err) {


i get an error:

mysql-orm WARN cid:5, qid:18  error = {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","index":0}; sql=
        INSERT INTO `status`
        SET
                `_id` = 0,
                `name` = 'server',
                `state` = 'updating'
        ON DUPLICATE KEY UPDATE
                `_id` = VALUES(`_id`),
                `name` = VALUES(`name`),
                `state` = VALUES(`state`)


the table has 6 columns. i do not get the error if i pass all 6 columns in the json filter.

schema is 

   status: {
         _id: { type: 'int' }, name: { type: 'varchar(50)' }, state: { type: 'varchar(128)' }, progress: { type: 'int' }, status_current: { type: 'int' }, total: { type: 'int' }
    },

i was curious the proper way to update less columns than exists in the table.

i looked at the examples on your page, but i didn’t figure it out. any light you can shed would be helpful.


thanks
Bryan

**Comment by battlesnake** [comment]
Interesting, I'll take a look at that when I'm healthy again (been down for a few days) - could you open a new issue for that problem?

Thanks

**Comment by bryanmi** [comment]
okay, thanks

i will first make a small example to verify i am not doing something stupid. also i feel like it worked last week, so it might be related to how i changed the structure of my program.

anyway i will let you know.

**Comment by battlesnake** [comment]
Thanks!

**Comment by battlesnake** [comment]
How did it go?

**Comment by bryanmi** [comment]
hi

unfortunately i have been really busy with work and haven’t had a chance to make a special test case.

for my application i can get things to work if i first do a db.load(“my_table”, { myField : “myValue” }, function() { } ), then pass that object to db.save(“my_table”, updatedObj, function() {} ) after modifying the fields i need to modify.

it would be cleaner if i can just pass a filter to save and have it just update that item.

my guess is it has something to do with either having a primary key specified or not. i am not really sure how when you do a save you determine whether to update the row or create a new row in DB. because in my usage, it is always either creating a new row or erroring out. 

anyway, for now i am fine with using it as is, but in a few weeks i will be working a DB intensive application that i may benefit from understanding how to efficiently use your update/save functions.

i will let you know

thx
Bryan

**Comment by bryanmi** [comment]
hi

i have been working a lot more with your library and maybe i was incorrectly assuming some things previously.

at any rate, everything i spoke about before is working for me, however, i have one huge blocking issue i haven’t solved yet.

i do not how to tell mysql to close the connection through your library.

so for example, i want to be able to do a:

connection.end();

to close the connection after i am done reading/writing.


the problem i have now is that each time i open my program i create a new connection which eventually runs over max connections out and i get error:

SELECT *
SRE2_SOFTWARE_UPDATER-2 (out):  FROM `versions`
SRE2_SOFTWARE_UPDATER-2 (out):  WHERE
SRE2_SOFTWARE_UPDATER-2 (out):          `name`='HD_PLAYER'
SRE2_SOFTWARE_UPDATER-2 (out): mysql-orm WARN cid:143, qid:5 error = {"code":"ER_CON_COUNT_ERROR","errno":1040,"fatal":true}; sql=

now i am assuming i need to end the connection to solve my problem, but maybe you are already handling closing the connection…i am not sure.

any suggestions? i have max connections set to 120 in ../mysql/etc/my.cnf

thanks
Bryan

**Comment by bryanmi** [comment]
hi again,

btw this is probably a typo bug in transaction.js

line 42

else {
	gotConnection(this.conncetion);
}

not sure if that contributes to my connection count error or not.

thx
Bryan

**Comment by battlesnake** [comment]
I've corrected that typo.  I coded this module on a friend's laptop which had a fresh Vim install, so there was no linting / code-quality configured - apologies for the fairly crap quality!

Let me know if this fixes your problem.

**Comment by bryanmi** [comment]
thx, VIM is….

also, i was not sure if you already were handling closing the mysql connection or not somewhere in your code…I only did a cursory check... 

so i added:

ORM.prototype.close = function (callback) {
	this.connection.end();
	callback();
};

since my application starts and stops many times (hundreds/thousands) over the runtime of the system, and in my application i call “create”, i needed a way to “close” the connection, otherwise the database would bark at me with:

SELECT *
SRE2_SOFTWARE_UPDATER-2 (out):  FROM `versions`
SRE2_SOFTWARE_UPDATER-2 (out):  WHERE
SRE2_SOFTWARE_UPDATER-2 (out):          `name`='HD_PLAYER'
SRE2_SOFTWARE_UPDATER-2 (out): mysql-orm WARN cid:143, qid:5 error = {"code":"ER_CON_COUNT_ERROR","errno":1040,"fatal":true}; sql=

calling close at the end of my program fixed the problem.

currently i am not updating to the latest version of your lib because i do not want my changes blown away, nor do i want to force my changes on you.

if you decide to add the close functionality (if you feel it was even needed), let me know so then i can re-sync with your lib from time to time.

thx
Bryan
